### ISSUE TITLE
4060ti16GB先后尝试了Qwen3.6-35B-A3B、Qwen3-30B-A3B、Qwen3-14B三个模型都没能跑起来

### ISSUE THREAD

**Issue by alasion** [val1813/kaiwu#8]
PS E:\Kaiwu> kaiwu run "E:\Kaiwu\Qwen3-14B-Q5_K_M.gguf"

██╗  ██╗ █████╗ ██╗██╗    ██╗██╗   ██╗
██║ ██╔╝██╔══██╗██║██║    ██║██║   ██║
█████╔╝ ███████║██║██║ █╗ ██║██║   ██║
██╔═██╗ ██╔══██║██║██║███╗██║██║   ██║
██║  ██╗██║  ██║██║╚███╔███╔╝╚██████╔╝
╚═╝  ╚═╝╚═╝  ╚═╝╚═╝ ╚══╝╚══╝  ╚═════╝
本地大模型部署器 vv0.1.5 · llama.cpp b8864
by llmbbs.ai · 本地 AI 技术社区

[1/6] Probing hardware...
      GPU: NVIDIA GeForce RTX 4060 Ti (SM89, 16380 MB VRAM, 288 GB/s)
      RAM: 63 GB DDR5
      OS:  windows amd64
      ⚠️  CUDA 13.2 detected — known bug with low-bit quantization
      If you see garbled output, downgrade driver to CUDA 13.1

[2/6] Selecting configuration...
      Model:  Qwen3-14B (dense, 14B)
      Quant:  Q5_K_M (9.8 GB)
      Mode:   full_gpu
      Accel:  Flash Attention

[3/6] Checking files...
      Using bundled iso3 binary: llama-server-cuda.exe
      Binary: llama-server-cuda.exe [cached]
      Model:  Qwen3-14B-Q5_K_M.gguf [cached]

[4/6] Preflight check...
      llama-server 不支持 iso3，回退到 q8_0/q4_0
      ✓ VRAM sufficient

[5/6] Warmup benchmark...
      Probe 1: ctx=32K ... OOM
      Probe 2: ctx=16K ... OOM
      Probe 3: ctx=8K ... OOM
      ⚠️  Warmup failed: all ctx probes failed (tried down to 4K)
      Using default parameters

[6/6] Starting server...
Waiting for llama-server to be ready (port 11434)...
      ⚠️  显存不足，降低上下文至 16K 重试...
Waiting for llama-server to be ready (port 11434)...
      ⚠️  显存不足，降低上下文至 8K 重试...
Waiting for llama-server to be ready (port 11434)...
Error: failed to start llama-server: 连续 3 次启动失败，即使最小上下文(4K)也无法运行

  NVIDIA GeForce RTX 4060 Ti: 16380 MB VRAM
  模型 Qwen3-14B: ~10024 MB
  KV cache (4K, q4_0): ~160 MB
  预估总需: ~11208 MB

  建议:
  1. 运行 kaiwu run qwen3-14b-q5_k_m --reset 重新探测参数
  2. 模型较小但仍 OOM，可能是参数配置问题，请升级到最新版本

Usage:
  kaiwu run <model> [flags]

Flags:
      --bench                 Run benchmark after starting
      --ctx-size int          手动指定上下文大小（0=自动）
      --fast                  Skip warmup, use cached profile
  -h, --help                  help for run
      --llama-server string   使用自定义 llama-server 二进制（完整路径）
      --reset                 清除缓存，重新 warmup 探测最优参数

**Comment by Seshiria** [comment]
可能作者是在linux测试,所以windwos流程有问题没测出来.
windows用户第一次使用需要以下操作步骤:

1,解压release到任意一个文件夹,
2,双击运行一次llama-server-cuda.exe,系统默认会拦截运行,解除.
3,下载openssl3 https://slproweb.com/products/Win32OpenSSL.html 安装.

然后正常运行就可以了.

**Comment by alasion** [comment]
某个缓存导致的，升级到最新版，清除掉所有缓存解决了
