### ISSUE TITLE
3090 运行故障

### ISSUE THREAD

**Issue by stefwoo** [val1813/kaiwu#9]
kaiwu.exe run .\Qwen3.6-35B-A3B-UD-IQ4_NL.gguf

██╗  ██╗ █████╗ ██╗██╗    ██╗██╗   ██╗
██║ ██╔╝██╔══██╗██║██║    ██║██║   ██║
█████╔╝ ███████║██║██║ █╗ ██║██║   ██║
██╔═██╗ ██╔══██║██║██║███╗██║██║   ██║
██║  ██╗██║  ██║██║╚███╔███╔╝╚██████╔╝
╚═╝  ╚═╝╚═╝  ╚═╝╚═╝ ╚══╝╚══╝  ╚═════╝
本地大模型部署器 vv0.1.6 · llama.cpp b8864
by llmbbs.ai · 本地 AI 技术社区

[1/6] Probing hardware...
      GPU: NVIDIA GeForce RTX 3090 (SM86, 24576 MB VRAM, 936 GB/s)
      RAM: 63 GB DDR4
      OS:  windows amd64

[2/6] Selecting configuration...
      Model:  Qwen3.6-35B-A3B (moe, 28B total / 1B active)
      Quant:  Q25 (16.8 GB)
      Mode:   full_gpu
      Accel:  Flash Attention + SWA-Full (hybrid arch)

[3/6] Checking files...
      Using bundled iso3 binary: llama-server-cuda.exe
      Binary: llama-server-cuda.exe [cached]
      Model:  Qwen3.6-35B-A3B-UD-IQ4_NL.gguf [cached]

[4/6] Preflight check...
      ✓ VRAM sufficient

[5/6] Warmup benchmark...
      Probe 1: ctx=256K ... OOM
      Probe 2: ctx=128K ... OOM
      Probe 3: ctx=64K ... OOM
      Probe 4: ctx=32K ... OOM
      Probe 5: ctx=16K ... OOM
      Probe 6: ctx=8K ... OOM
      ⚠️  Warmup failed: all ctx probes failed (tried down to 4K)
      Using default parameters

[6/6] Starting server...
Waiting for llama-server to be ready (port 11434)...
      ⚠️  显存不足，降低上下文至 64K 重试...
Waiting for llama-server to be ready (port 11434)...
      ⚠️  显存不足，降低上下文至 32K 重试...
Waiting for llama-server to be ready (port 11434)...
Error: failed to start llama-server: 3 次启动均失败，建议选择更小的模型
Usage:
  kaiwu run <model> [flags]

Flags:
      --bench                 Run benchmark after starting
      --ctx-size int          手动指定上下文大小（0=自动）
      --fast                  Skip warmup, use cached profile
  -h, --help                  help for run
      --llama-server string   使用自定义 llama-server 二进制（完整路径）
      --reset                 清除缓存，重新 warmup 探测最优参数

**Comment by shen09gsd** [comment]
有试过安装Win64OpenSSL-3_6_2.exe这个吗？我刚刚自己也碰到类似问题，装了这个好了

**Comment by stefwoo** [comment]
kaiwu.exe run .\gemma-4-31B-it-IQ4_NL.gguf

██╗  ██╗ █████╗ ██╗██╗    ██╗██╗   ██╗
██║ ██╔╝██╔══██╗██║██║    ██║██║   ██║
█████╔╝ ███████║██║██║ █╗ ██║██║   ██║
██╔═██╗ ██╔══██║██║██║███╗██║██║   ██║
██║  ██╗██║  ██║██║╚███╔███╔╝╚██████╔╝
╚═╝  ╚═╝╚═╝  ╚═╝╚═╝ ╚══╝╚══╝  ╚═════╝
本地大模型部署器 vv0.1.6 · llama.cpp b8864
by llmbbs.ai · 本地 AI 技术社区

[1/6] Probing hardware...
      GPU: NVIDIA GeForce RTX 3090 (SM86, 24576 MB VRAM, 936 GB/s)
      RAM: 63 GB DDR4
      OS:  windows amd64

[2/6] Selecting configuration...
      Model:  Gemma-4-31B-It (dense, 27B)
      Quant:  Q25 (16.1 GB)
      Mode:   full_gpu
      Accel:  Flash Attention

[3/6] Checking files...
      Using bundled iso3 binary: llama-server-cuda.exe
      Binary: llama-server-cuda.exe [cached]
      Model:  gemma-4-31B-it-IQ4_NL.gguf [cached]

[4/6] Preflight check...
      llama-server 不支持 iso3，回退到 q8_0/q4_0
      ✓ VRAM sufficient

[5/6] Warmup benchmark...
      Probe 1: ctx=64K ... OOM
      Probe 2: ctx=32K ... OOM
      Probe 3: ctx=16K ... OOM
      Probe 4: ctx=8K ...

**Comment by stefwoo** [comment]
kaiwu.exe run .\Qwen3.5-9B-Q4_K_M.gguf

██╗  ██╗ █████╗ ██╗██╗    ██╗██╗   ██╗
██║ ██╔╝██╔══██╗██║██║    ██║██║   ██║
█████╔╝ ███████║██║██║ █╗ ██║██║   ██║
██╔═██╗ ██╔══██║██║██║███╗██║██║   ██║
██║  ██╗██║  ██║██║╚███╔███╔╝╚██████╔╝
╚═╝  ╚═╝╚═╝  ╚═╝╚═╝ ╚══╝╚══╝  ╚═════╝
本地大模型部署器 vv0.1.6 · llama.cpp b8864
by llmbbs.ai · 本地 AI 技术社区

[1/6] Probing hardware...
      GPU: NVIDIA GeForce RTX 3090 (SM86, 24576 MB VRAM, 936 GB/s)
      RAM: 63 GB DDR4
      OS:  windows amd64

[2/6] Selecting configuration...
      Model:  Qwen3.5-9B (dense, 10B)
      Quant:  Q4_K_M (5.3 GB)
      Mode:   full_gpu
      Accel:  Flash Attention + SWA-Full (hybrid arch)

[3/6] Checking files...
      Using bundled iso3 binary: llama-server-cuda.exe
      Binary: llama-server-cuda.exe [cached]
      Model:  Qwen3.5-9B-Q4_K_M.gguf [cached]

[4/6] Preflight check...
      ✓ VRAM sufficient

[5/6] Warmup benchmark...
      Probe 1: ctx=128K ... OOM
      Probe 2: ctx=64K ...

**Comment by shen09gsd** [comment]
██╗  ██╗ █████╗ ██╗██╗    ██╗██╗   ██╗
██║ ██╔╝██╔══██╗██║██║    ██║██║   ██║
█████╔╝ ███████║██║██║ █╗ ██║██║   ██║
██╔═██╗ ██╔══██║██║██║███╗██║██║   ██║
██║  ██╗██║  ██║██║╚███╔███╔╝╚██████╔╝
╚═╝  ╚═╝╚═╝  ╚═╝╚═╝ ╚══╝╚══╝  ╚═════╝
本地大模型部署器 vv0.1.6 · llama.cpp b8864
by llmbbs.ai · 本地 AI 技术社区

[1/6] Probing hardware...
      GPU: NVIDIA GeForce RTX 4060 Ti (SM89, 16380 MB VRAM, 288 GB/s)
      RAM: 31 GB UNKNOWN
      OS:  windows amd64
      ⚠️  CUDA 13.2 detected — known bug with low-bit quantization
      If you see garbled output, downgrade driver to CUDA 13.1

[2/6] Selecting configuration...
      Model:  Qwen3 30B Gptq Fp16 (moe, 31B total / 2B active)
      Quant:  Q4_K_M (17.3 GB)
      Mode:   moe_offload (experts on CPU)
      Accel:  Flash Attention

[3/6] Checking files...
      Using bundled iso3 binary: llama-server-cuda.exe
      Binary: llama-server-cuda.exe [cached]
      Model:  Qwen3-30B-A3B-Q4_K_M.gguf [cached]

[4/6] Preflight check...
      llama-server 不支持 iso3，回退到 q8_0/q4_0
      ⚠️  RAM 当前可用 7.1 GB，模型需要 15.6 GB
      ✓ VRAM sufficient

[5/6] Warmup benchmark...
      使用上次配置（8K ctx · 14.9 tok/s · 0 小时前）
      ✓ 14.9 tok/s

[6/6] Starting server...
Waiting for llama-server to be ready (port 11434)...
      llama-server started (PID 21232, port 11434)
      Kaiwu proxy started (port 11435)

  ┌─────────────────────────────────────────────────┐
2026/04/25 18:52:31 Kaiwu proxy listening on :11435 → llama-server :11434
  │  Ready — Qwen3 30B Gptq Fp16 @ 14.9 tok/s          │
  │  API: http://127.0.0.1:11435/v1/chat/completions    │
  │  模型文件夹: C:\Users\shen09\.kaiwu\models          │
  └─────────────────────────────────────────────────┘

  运行 kaiwu inject 接入 IDE · Ctrl+C 停止
─ 实时监控 · 空载 ─────────────────── 每 2s 刷新 ─
  reuse:512 · KV:f16 · 8K ctx · ub128
  速度          显存           内存        GPU      温度
  — tok/s     7.6/16 GB    —        33%      28°C
  [..........] [====......] [..........] [===.......] [==........]
─────────────────────────────────────────────────────────
  上下文  [....................]  0.0K / 8K  余 8.0K
2026/04/25 19:08:50 repetition detected in stream, injecting stop
正在停止服务...
✓ llama-server 已停止
✓ Kaiwu proxy 已停止

感谢使用 Kaiwu · 访问 llmbbs.ai 获取更多本地 AI 技巧和模型推荐
PS C:\Users\shen09> kaiwu run gemma-4-26B-A4B-it-MXFP4_MOE.gguf

██╗  ██╗ █████╗ ██╗██╗    ██╗██╗   ██╗
██║ ██╔╝██╔══██╗██║██║    ██║██║   ██║
█████╔╝ ███████║██║██║ █╗ ██║██║   ██║
██╔═██╗ ██╔══██║██║██║███╗██║██║   ██║
██║  ██╗██║  ██║██║╚███╔███╔╝╚██████╔╝
╚═╝  ╚═╝╚═╝  ╚═╝╚═╝ ╚══╝╚══╝  ╚═════╝
本地大模型部署器 vv0.1.6 · llama.cpp b8864
by llmbbs.ai · 本地 AI 技术社区

[1/6] Probing hardware...
      GPU: NVIDIA GeForce RTX 4060 Ti (SM89, 16380 MB VRAM, 288 GB/s)
      RAM: 31 GB UNKNOWN
      OS:  windows amd64
      ⚠️  CUDA 13.2 detected — known bug with low-bit quantization
      If you see garbled output, downgrade driver to CUDA 13.1

[2/6] Selecting configuration...
      Model:  Gemma-4-26B-A4B-It (moe, 26B total / 2B active)
      Quant:  Q38 (15.5 GB)
      Mode:   full_gpu
      Accel:  Flash Attention

[3/6] Checking files...
      Using bundled iso3 binary: llama-server-cuda.exe
      Binary: llama-server-cuda.exe [cached]
      Model:  gemma-4-26B-A4B-it-MXFP4_MOE.gguf [cached]

[4/6] Preflight check...
      llama-server 不支持 iso3，回退到 q8_0/q4_0
      ✓ VRAM sufficient

[5/6] Warmup benchmark...
      Probe 1: ctx=8K ...
PS C:\Users\shen09> kaiwu run gemma-4-26B-A4B-it-MXFP4_MOE.gguf --reset

██╗  ██╗ █████╗ ██╗██╗    ██╗██╗   ██╗
██║ ██╔╝██╔══██╗██║██║    ██║██║   ██║
█████╔╝ ███████║██║██║ █╗ ██║██║   ██║
██╔═██╗ ██╔══██║██║██║███╗██║██║   ██║
██║  ██╗██║  ██║██║╚███╔███╔╝╚██████╔╝
╚═╝  ╚═╝╚═╝  ╚═╝╚═╝ ╚══╝╚══╝  ╚═════╝
本地大模型部署器 vv0.1.6 · llama.cpp b8864
by llmbbs.ai · 本地 AI 技术社区

[1/6] Probing hardware...
      GPU: NVIDIA GeForce RTX 4060 Ti (SM89, 16380 MB VRAM, 288 GB/s)
      RAM: 31 GB UNKNOWN
      OS:  windows amd64
      ⚠️  CUDA 13.2 detected — known bug with low-bit quantization
      If you see garbled output, downgrade driver to CUDA 13.1

[2/6] Selecting configuration...
      Model:  Gemma-4-26B-A4B-It (moe, 26B total / 2B active)
      Quant:  Q38 (15.5 GB)
      Mode:   full_gpu
      Accel:  Flash Attention

[3/6] Checking files...
      Using bundled iso3 binary: llama-server-cuda.exe
      Binary: llama-server-cuda.exe [cached]
      Model:  gemma-4-26B-A4B-it-MXFP4_MOE.gguf [cached]

[4/6] Preflight check...
      llama-server 不支持 iso3，回退到 q8_0/q4_0
      ✓ VRAM sufficient

[5/6] Warmup benchmark...
      已清除缓存，重新探测
      Probe 1: ctx=8K ...
PS C:\Users\shen09> kaiwu run Qwen3-30B-A3B-Q4_K_M.gguf

██╗  ██╗ █████╗ ██╗██╗    ██╗██╗   ██╗
██║ ██╔╝██╔══██╗██║██║    ██║██║   ██║
█████╔╝ ███████║██║██║ █╗ ██║██║   ██║
██╔═██╗ ██╔══██║██║██║███╗██║██║   ██║
██║  ██╗██║  ██║██║╚███╔███╔╝╚██████╔╝
╚═╝  ╚═╝╚═╝  ╚═╝╚═╝ ╚══╝╚══╝  ╚═════╝
本地大模型部署器 vv0.1.6 · llama.cpp b8864
by llmbbs.ai · 本地 AI 技术社区

[1/6] Probing hardware...
      GPU: NVIDIA GeForce RTX 4060 Ti (SM89, 16380 MB VRAM, 288 GB/s)
      RAM: 31 GB UNKNOWN
      OS:  windows amd64
      ⚠️  CUDA 13.2 detected — known bug with low-bit quantization
      If you see garbled output, downgrade driver to CUDA 13.1

[2/6] Selecting configuration...
      Model:  Qwen3 30B Gptq Fp16 (moe, 31B total / 2B active)
      Quant:  Q4_K_M (17.3 GB)
      Mode:   moe_offload (experts on CPU)
      Accel:  Flash Attention

[3/6] Checking files...
      Using bundled iso3 binary: llama-server-cuda.exe
      Binary: llama-server-cuda.exe [cached]
      Model:  Qwen3-30B-A3B-Q4_K_M.gguf [cached]

[4/6] Preflight check...
      llama-server 不支持 iso3，回退到 q8_0/q4_0
      ⚠️  RAM 当前可用 9.7 GB，模型需要 15.6 GB
      ✓ VRAM sufficient

[5/6] Warmup benchmark...
      使用上次配置（8K ctx · 14.9 tok/s · 1 小时前）
      ✓ 14.9 tok/s

[6/6] Starting server...
Waiting for llama-server to be ready (port 11434)...
      llama-server started (PID 15324, port 11434)
      Kaiwu proxy started (port 11435)

  ┌─────────────────────────────────────────────────┐
2026/04/25 19:23:03 Kaiwu proxy listening on :11435 → llama-server :11434
  │  Ready — Qwen3 30B Gptq Fp16 @ 14.9 tok/s          │
  │  API: http://127.0.0.1:11435/v1/chat/completions    │
  │  模型文件夹: C:\Users\shen09\.kaiwu\models          │
  └─────────────────────────────────────────────────┘

  运行 kaiwu inject 接入 IDE · Ctrl+C 停止
─ 实时监控 · 空载 ─────────────────── 每 2s 刷新 ─
  reuse:512 · KV:f16 · 8K ctx · ub128
  速度          显存           内存        GPU      温度
  — tok/s     7.2/16 GB    —        6%      29°CC
  [..........] [====......] [..........] [..........] [==........]
─────────────────────────────────────────────────────────
  上下文  [....................]  0.0K / 8K  余 8.0K

正在停止服务...
✓ llama-server 已停止
✓ Kaiwu proxy 已停止

感谢使用 Kaiwu · 访问 llmbbs.ai 获取更多本地 AI 技巧和模型推荐
PS C:\Users\shen09> kaiwu run Qwen3.6-35B-A3B-UD-IQ4_NL.gguf

██╗  ██╗ █████╗ ██╗██╗    ██╗██╗   ██╗
██║ ██╔╝██╔══██╗██║██║    ██║██║   ██║
█████╔╝ ███████║██║██║ █╗ ██║██║   ██║
██╔═██╗ ██╔══██║██║██║███╗██║██║   ██║
██║  ██╗██║  ██║██║╚███╔███╔╝╚██████╔╝
╚═╝  ╚═╝╚═╝  ╚═╝╚═╝ ╚══╝╚══╝  ╚═════╝
本地大模型部署器 vv0.1.6 · llama.cpp b8864
by llmbbs.ai · 本地 AI 技术社区

[1/6] Probing hardware...
      GPU: NVIDIA GeForce RTX 4060 Ti (SM89, 16380 MB VRAM, 288 GB/s)
      RAM: 31 GB UNKNOWN
      OS:  windows amd64
      ⚠️  CUDA 13.2 detected — known bug with low-bit quantization
      If you see garbled output, downgrade driver to CUDA 13.1

[2/6] Selecting configuration...
      Model:  Qwen3.6-35B-A3B (moe, 28B total / 1B active)
      Quant:  Q25 (16.8 GB)
      Mode:   moe_offload (experts on CPU)
      Accel:  Flash Attention + SWA-Full (hybrid arch)

[3/6] Checking files...
      Using bundled iso3 binary: llama-server-cuda.exe
      Binary: llama-server-cuda.exe [cached]
      Model:  Qwen3.6-35B-A3B-UD-IQ4_NL.gguf [cached]

[4/6] Preflight check...
      ⚠️  RAM 当前可用 11.5 GB，模型需要 15.1 GB
      ✓ VRAM sufficient

[5/6] Warmup benchmark...
      Warning: RAM tight: 11.5 GB free, need ~21.5 GB (15.1 GB model + 6.4 GB reserve)
      Probe 1: ctx=256K ... 10.5 tok/s (< 18, too slow)
      Probe 2: ctx=128K ... 12.9 tok/s (< 18, too slow)
      Probe 3: ctx=64K ... 11.8 tok/s (< 18, too slow)
      Probe 4: ctx=32K ... 12.6 tok/s (< 18, too slow)
      Probe 5: ctx=16K ... 12.3 tok/s (< 18, too slow)
      Probe 6: ctx=8K ... 10.5 tok/s (< 18, too slow)
      Tune ubatch: ub=128 → 13.6 tok/s; ub=512 → 15.5 tok/s;
      ✓ 15.5 tok/s @ 128K ctx
      Saved profile: C:\Users\shen09\.kaiwu\profiles\qwen3.6-35b-a3b-ud-iq4_nl_sm89_16380mb_unknown.json
      ✓ 15.5 tok/s

[6/6] Starting server...
Waiting for llama-server to be ready (port 11434)...
      llama-server started (PID 11844, port 11434)
      Kaiwu proxy started (port 11435)

  ┌─────────────────────────────────────────────────┐
  │  Ready — Qwen3.6-35B-A3B @ 15.5 tok/s              │
  │  API: http://127.0.0.1:11435/v1/chat/completions    │
  │  模型文件夹: C:\Users\shen09\.kaiwu\models          │
  └─────────────────────────────────────────────────┘

  运行 kaiwu inject 接入 IDE · Ctrl+C 停止

2026/04/25 19:33:39 Kaiwu proxy listening on :11435 → llama-server :11434
─ 实时监控 · 空载 ─────────────────── 每 2s 刷新 ─
  reuse:1024 · KV:f16 · 128K ctx · ub512
  速度          显存           内存        GPU      温度
  — tok/s     10.4/16 GB    —        1%      30°CC
  [..........] [======....] [..........] [..........] [===.......]
─────────────────────────────────────────────────────────
正常会这样显示，试着安装Win64OpenSSL-3_6_2.exe依赖，https://slproweb.com/products/Win32OpenSSL.html

**Comment by stefwoo** [comment]
> 有试过安装Win64OpenSSL-3_6_2.exe这个吗？我刚刚自己也碰到类似问题，装了这个好了



有效。感谢。

**Comment by stefwoo** [comment]
但是这个运行有点问题：9B用满现存，64k输出20tps

kaiwu.exe run .\Qwen3.5-9B-Q4_K_M.gguf

██╗  ██╗ █████╗ ██╗██╗    ██╗██╗   ██╗
██║ ██╔╝██╔══██╗██║██║    ██║██║   ██║
█████╔╝ ███████║██║██║ █╗ ██║██║   ██║
██╔═██╗ ██╔══██║██║██║███╗██║██║   ██║
██║  ██╗██║  ██║██║╚███╔███╔╝╚██████╔╝
╚═╝  ╚═╝╚═╝  ╚═╝╚═╝ ╚══╝╚══╝  ╚═════╝
本地大模型部署器 vv0.1.6 · llama.cpp b8864
by llmbbs.ai · 本地 AI 技术社区

[1/6] Probing hardware...
      GPU: NVIDIA GeForce RTX 3090 (SM86, 24576 MB VRAM, 936 GB/s)
      RAM: 63 GB DDR4
      OS:  windows amd64

[2/6] Selecting configuration...
      Model:  Qwen3.5-9B (dense, 10B)
      Quant:  Q4_K_M (5.3 GB)
      Mode:   full_gpu
      Accel:  Flash Attention + SWA-Full (hybrid arch)

[3/6] Checking files...
      Using bundled iso3 binary: llama-server-cuda.exe
      Binary: llama-server-cuda.exe [cached]
      Model:  Qwen3.5-9B-Q4_K_M.gguf [cached]

[4/6] Preflight check...
      ✓ VRAM sufficient

[5/6] Warmup benchmark...
      Probe 1: ctx=8K ... 106.2 tok/s
      Probe 2: ctx=16K ... 49.8 tok/s
      Probe 3: ctx=32K ... 21.2 tok/s
      Probe 4: ctx=64K ... 20.1 tok/s
      Tune ubatch: ub=128 → 21.4 tok/s; ub=512 → 15.6 tok/s;
      ✓ 21.4 tok/s @ 64K ctx
      Saved profile: C:\Users\stewoo\.kaiwu\profiles\qwen3.5-9b-q4_k_m_sm86_24576mb_ddr4.json
      ✓ 21.4 tok/s

[6/6] Starting server...
Waiting for llama-server to be ready (port 11434)...
      llama-server started (PID 17720, port 11434)
      Kaiwu proxy started (port 11435)
2026/04/25 19:29:03 Kaiwu proxy listening on :11435 → llama-server :11434

  ┌─────────────────────────────────────────────────┐
  │  Ready — Qwen3.5-9B @ 21.4 tok/s                   │
  │  API: http://127.0.0.1:11435/v1/chat/completions    │
  │  模型文件夹: C:\Users\stewoo\.kaiwu\models          │
  └─────────────────────────────────────────────────┘

  运行 kaiwu inject 接入 IDE · Ctrl+C 停止
─ 实时监控 · 空载 ─────────────────── 每 2s 刷新 ─
  reuse:1024 · KV:f16 · 64K ctx · ub128 · mlock
  速度          显存           内存        GPU      温度
  — tok/s     23.6/24 GB    37.7/64 GB   0%      35°CC
  [..........] [=========.] [=====.....] [..........] [===.......]
─────────────────────────────────────────────────────────
  上下文  [....................]  0.0K / 64K  余 64.0K

⚠️  显存即将用满，推理可能中断

**Comment by shen09gsd** [comment]
感觉这个项目是把上下文的显存空间提前预留了，这个错误如果官方能在windows版中自动安装就好了，就不会有这个问题，或者文档中指引用户去安装，主要没有任何提示，我自己运行了项目中的 llama-server-cuda.exe 文件才发现缺失这个依赖

**Comment by shen09gsd** [comment]
还有多次运行不同模型显存和内存占用好像是叠加的。。。我尝试手动通过任务管理器结束进程可以清空显存和内存占用

**Comment by val1813** [comment]
> 感觉这个项目是把上下文的显存空间提前预留了，这个错误如果官方能在windows版中自动安装就好了，就不会有这个问题，或者文档中指引用户去安装，主要没有任何提示，我自己运行了项目中的 llama-server-cuda.exe 文件才发现缺失这个依赖

嗯 已经新增了dll不再报错了

**Comment by val1813** [comment]
上述问题在0.2.0版本已经优化了 如果还有问题麻烦反馈下 我看到第一时间处理
